"""Change user and file connection

Revision ID: 1af3cd5b815f
Revises: bfbfb2a46fb6
Create Date: 2025-03-13 12:25:30.484923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af3cd5b815f'
down_revision: Union[str, None] = 'bfbfb2a46fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tblFile_user_id_fkey', 'tblFile', type_='foreignkey')
    op.drop_column('tblFile', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblFile', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tblFile_user_id_fkey', 'tblFile', 'tblUser', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
