"""исправлена обратная ссылка пользователя на преподавателя

Revision ID: 44695f3b687c
Revises: 1af3cd5b815f
Create Date: 2025-03-13 22:32:06.146257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44695f3b687c'
down_revision: Union[str, None] = '1af3cd5b815f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
