"""delete is_from_API lesson

Revision ID: 45864e2fd478
Revises: 73a7b8bd1813
Create Date: 2025-05-04 00:38:35.264251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45864e2fd478'
down_revision: Union[str, None] = '73a7b8bd1813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tblLesson', 'is_from_API')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblLesson', sa.Column('is_from_API', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
