"""Added enum file_type: document, photo, video, audio

Revision ID: 73a7b8bd1813
Revises: 44695f3b687c
Create Date: 2025-04-30 18:25:57.535994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a7b8bd1813'
down_revision: Union[str, None] = '44695f3b687c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    filetype_enum = sa.Enum('document', 'photo', 'video', 'audio', name='filetype')
    filetype_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblFile', sa.Column('file_type', sa.Enum('document', 'photo', 'video', 'audio', name='filetype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tblFile', 'file_type')
    # ### end Alembic commands ###
    op.execute("DROP TYPE filetype")
