"""Initial migration

Revision ID: bfbfb2a46fb6
Revises: 
Create Date: 2025-03-12 01:39:42.192888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = 'bfbfb2a46fb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblUser',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_petrsu_student', sa.Boolean(), nullable=False),
    sa.Column('group', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('tblTeacher',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('social_page_link', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('classroom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_from_API', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tblUser.user_id'], ),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_table('tblDiscipline',
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_from_API', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['tblTeacher.teacher_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tblUser.user_id'], ),
    sa.PrimaryKeyConstraint('discipline_id')
    )
    op.create_table('tblLesson',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('classroom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('periodicity_days', sa.Integer(), nullable=False),
    sa.Column('is_from_API', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['tblDiscipline.discipline_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tblUser.user_id'], ),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    op.create_table('tblTask',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('task_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('task_link', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('extra_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'done', 'submitted', name='status'), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['tblDiscipline.discipline_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tblUser.user_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('tblFile',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tblTask.task_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tblUser.user_id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblFile')
    op.drop_table('tblTask')
    op.drop_table('tblLesson')
    op.drop_table('tblDiscipline')
    op.drop_table('tblTeacher')
    op.drop_table('tblUser')
    # ### end Alembic commands ###
